version: "3.9"
services:
  clipnotes:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -r requirements.txt && uvicorn app_server:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - API_TOKENS=dev-token-please-change
      - DEFAULT_TENANT=localdev
      - STORAGE_PROVIDER=local
      - DATA_DIR=/app/data
      - MCP_SERVER_NAME=clipnotes-mcp
      - MCP_STATELESS_HTTP=true
