openapi: 3.0.3
info:
  title: ClipNotes API
  version: 1.0.0
servers:
  - url: https://your.domain.com
paths:
  /notes:
    post:
      summary: Save a chat snippet
      operationId: createNote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [content]
              properties:
                content: { type: string }
                tags: { type: array, items: { type: string } }
                topic: { type: string }
                source:
                  type: object
                  properties:
                    thread_title: { type: string }
                    msg_id: { type: string }
                    url: { type: string }
                context_before:
                  type: array
                  items:
                    type: object
                    properties:
                      role: { type: string, enum: [user, assistant, system] }
                      text: { type: string }
      responses:
        '200':
          description: OK
  /notes:
    get:
      summary: List recent
      parameters:
        - name: limit
          in: query
          schema: { type: integer, default: 5 }
      responses:
        '200':
          description: OK
  /notes/search:
    get:
      summary: Search notes
      parameters:
        - name: q
          in: query
          required: true
          schema: { type: string }
        - name: limit
          in: query
          schema: { type: integer, default: 10 }
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
